/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.40
 * Generated at: 2025-04-30 09:01:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"id\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("    <title>Beranda | Aplikasi JSP</title>\r\n");
      out.write("    <!-- Panggil Bootstrap lokal -->\r\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- Adding Bootstrap Icons CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- Custom styles inside head -->\r\n");
      out.write("    <style>\r\n");
      out.write("        :root {\r\n");
      out.write("            --dark-bg: #121212;\r\n");
      out.write("            --dark-card: #1e1e1e;\r\n");
      out.write("            --dark-light: #2d2d2d;\r\n");
      out.write("            --accent-purple: #bb86fc;\r\n");
      out.write("            --accent-blue: #03dac6;\r\n");
      out.write("            --accent-pink: #cf6679;\r\n");
      out.write("            --text-primary: #e1e1e1;\r\n");
      out.write("            --text-secondary: #b0b0b0;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* Hero section enhancements */\r\n");
      out.write("        .bg-gradient {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            background: none !important;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* Add the hero background image overlay */\r\n");
      out.write("        .hero-background {\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            background-image: url('https://images.unsplash.com/photo-1745750747228-d7ae37cba3a5?q=80&w=2072&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D');\r\n");
      out.write("            background-size: cover;\r\n");
      out.write("            background-position: center;\r\n");
      out.write("            background-repeat: no-repeat;\r\n");
      out.write("            z-index: -10;\r\n");
      out.write("            filter: brightness(0.6);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* Page overlay to darken the background image slightly */\r\n");
      out.write("        .overlay {\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            background: linear-gradient(135deg, rgba(18, 18, 18, 0.7), rgba(32, 10, 64, 0.8));\r\n");
      out.write("            z-index: -5;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        body {\r\n");
      out.write("            background-color: transparent;\r\n");
      out.write("            color: var(--text-primary);\r\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .navbar {\r\n");
      out.write("            padding: 0.8rem 1rem;\r\n");
      out.write("            background-color: rgba(18, 18, 18, 0.6) !important;\r\n");
      out.write("            backdrop-filter: blur(15px);\r\n");
      out.write("            border-bottom: 1px solid rgba(255, 255, 255, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .navbar-brand {\r\n");
      out.write("            font-size: 1.5rem;\r\n");
      out.write("            color: var(--accent-purple) !important;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .nav-link {\r\n");
      out.write("            font-size: 1.1rem;\r\n");
      out.write("            margin: 0 0.2rem;\r\n");
      out.write("            color: var(--text-primary) !important;\r\n");
      out.write("            transition: color 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .nav-link:hover, .nav-link.active {\r\n");
      out.write("            color: var(--accent-purple) !important;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .btn-light {\r\n");
      out.write("            background-color: var(--dark-light);\r\n");
      out.write("            color: var(--text-primary);\r\n");
      out.write("            border: none;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .btn-light:hover {\r\n");
      out.write("            background-color: var(--accent-purple);\r\n");
      out.write("            color: #000;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .btn-primary {\r\n");
      out.write("            background: linear-gradient(45deg, var(--accent-purple), var(--accent-blue));\r\n");
      out.write("            border: none;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .btn {\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .btn:hover {\r\n");
      out.write("            transform: translateY(-3px);\r\n");
      out.write("            box-shadow: 0 5px 15px rgba(187, 134, 252, 0.3);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .bg-gradient {\r\n");
      out.write("            background: linear-gradient(135deg, #400080 0%, #0066a6 100%) !important;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .bg-light {\r\n");
      out.write("            background-color: var(--dark-light) !important;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .opacity-90 {\r\n");
      out.write("            opacity: 0.9;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* Card styling */\r\n");
      out.write("        .card-title {\r\n");
      out.write("            font-size: 1.5rem;\r\n");
      out.write("            color: rgba(255, 255, 255);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card {\r\n");
      out.write("            background-color: rgba(30, 30, 30, 0.7);\r\n");
      out.write("            backdrop-filter: blur(10px);\r\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.1);\r\n");
      out.write("            transition: transform 0.3s ease, box-shadow 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .card:hover {\r\n");
      out.write("            transform: translateY(-5px);\r\n");
      out.write("            box-shadow: 0 10px 20px rgba(187, 134, 252, 0.2) !important;\r\n");
      out.write("            border-color: var(--accent-purple);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* Feature icon styling */\r\n");
      out.write("        .feature-icon {\r\n");
      out.write("            display: inline-flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            width: 70px;\r\n");
      out.write("            height: 70px;\r\n");
      out.write("            font-size: 1.8rem;\r\n");
      out.write("            box-shadow: 0 0.125rem 0.25rem rgba(0, 0, 0, 0.3);\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .icon-security {\r\n");
      out.write("            background: linear-gradient(135deg, #bb86fc, #9546fa);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .icon-performance {\r\n");
      out.write("            background: linear-gradient(135deg, #03dac6, #018786);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .icon-responsive {\r\n");
      out.write("            background: linear-gradient(135deg, #cf6679, #b4354e);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .text-muted {\r\n");
      out.write("            color: var(--text-secondary) !important;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* CTA section */\r\n");
      out.write("        .cta-container {\r\n");
      out.write("            border-radius: 16px;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.1);\r\n");
      out.write("            box-shadow: 0 8px 32px rgba(0, 0, 0, 0.2);\r\n");
      out.write("            background: rgba(24, 24, 24, 0.6);\r\n");
      out.write("            backdrop-filter: blur(15px);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* Footer styling */\r\n");
      out.write("        footer {\r\n");
      out.write("            background-color: rgba(10, 10, 10, 0.8) !important;\r\n");
      out.write("            backdrop-filter: blur(15px);\r\n");
      out.write("            border-top: 1px solid rgba(255, 255, 255, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        footer a.link-light {\r\n");
      out.write("            color: var(--text-secondary) !important;\r\n");
      out.write("            transition: color 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        footer a.link-light:hover {\r\n");
      out.write("            color: var(--accent-purple) !important;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        footer .social-icon {\r\n");
      out.write("            display: inline-flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            width: 40px;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            background-color: var(--dark-light);\r\n");
      out.write("            transition: all 0.3s;\r\n");
      out.write("            margin-left: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        footer .social-icon:hover {\r\n");
      out.write("            transform: translateY(-3px);\r\n");
      out.write("            background-color: var(--accent-purple);\r\n");
      out.write("            color: #000 !important;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* Smooth scroll behavior */\r\n");
      out.write("        html {\r\n");
      out.write("            scroll-behavior: smooth;\r\n");
      out.write("            scrollbar-color: var(--accent-purple) var(--dark-bg);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        ::-webkit-scrollbar {\r\n");
      out.write("            width: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        ::-webkit-scrollbar-track {\r\n");
      out.write("            background: var(--dark-bg);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        ::-webkit-scrollbar-thumb {\r\n");
      out.write("            background: var(--accent-purple);\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* Neon text effect */\r\n");
      out.write("        .neon-text {\r\n");
      out.write("            color: var(--text-primary);\r\n");
      out.write("            text-shadow: 0 0 5px rgba(187, 134, 252, 0.5),\r\n");
      out.write("                         0 0 10px rgba(187, 134, 252, 0.3);\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Background image and overlay -->\r\n");
      out.write("    <div class=\"hero-background\"></div>\r\n");
      out.write("    <div class=\"overlay\"></div>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Enhanced Navbar with shadow and custom styling -->\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg shadow fixed-top\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <a class=\"navbar-brand fw-bold\" href=\"#\">\r\n");
      out.write("                <i class=\"bi bi-code-square me-2\"></i>Aplikasi JSP\r\n");
      out.write("            </a>\r\n");
      out.write("            <button class=\"navbar-toggler border-0\" type=\"button\" data-bs-toggle=\"collapse\"\r\n");
      out.write("                data-bs-target=\"#navbarNav\" aria-controls=\"navbarNav\" aria-expanded=\"false\"\r\n");
      out.write("                aria-label=\"Toggle navigation\">\r\n");
      out.write("                <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("                <ul class=\"navbar-nav ms-auto\">\r\n");
      out.write("                    <li class=\"nav-item\"><a class=\"nav-link active fw-semibold\" href=\"#\">Beranda</a></li>\r\n");
      out.write("                    <li class=\"nav-item\"><a class=\"nav-link fw-semibold\" href=\"#\">Tentang</a></li>\r\n");
      out.write("                    <li class=\"nav-item\"><a class=\"nav-link fw-semibold\" href=\"#\">Kontak</a></li>\r\n");
      out.write("                    <li class=\"nav-item ms-2\"><a class=\"btn btn-light rounded-pill px-3\" href=\"login.jsp\">Login</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Hero Section with Gradient Background -->\r\n");
      out.write("    <div class=\"py-5 bg-gradient\" style=\"padding-top: 8rem !important;\">\r\n");
      out.write("        <div class=\"container text-center py-5 glow-effect\">\r\n");
      out.write("            <h1 class=\"display-4 fw-bold text-white mb-3 neon-text\">Selamat Datang</h1>\r\n");
      out.write("            <p class=\"lead text-white opacity-90 mb-4\">Halaman utama aplikasi JSP dengan tampilan modern.</p>\r\n");
      out.write("            <a href=\"login.jsp\" class=\"btn btn-light btn-lg rounded-pill shadow px-5 py-3 fw-semibold\">\r\n");
      out.write("                <i class=\"bi bi-box-arrow-in-right me-2\"></i>Login Sekarang\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Features Section -->\r\n");
      out.write("    <div class=\"container py-5\">\r\n");
      out.write("        <div class=\"row text-center mb-5\">\r\n");
      out.write("            <div class=\"col-lg-8 mx-auto\">\r\n");
      out.write("                <h2 class=\"fw-bold neon-text\">Fitur Unggulan</h2>\r\n");
      out.write("                <p class=\"lead text-white\">Aplikasi JSP ini dilengkapi berbagai fitur untuk memudahkan pengguna.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row g-4\">\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("                <div class=\"card border-0 shadow h-100\">\r\n");
      out.write("                    <div class=\"card-body text-center p-4\">\r\n");
      out.write("                        <div class=\"feature-icon icon-security text-white rounded-circle mb-4\">\r\n");
      out.write("                            <i class=\"bi bi-shield-check\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h5 class=\"card-title fw-bold\">Keamanan Terjamin</h5>\r\n");
      out.write("                        <p class=\"card-text text-white\">Sistem keamanan berlapis dengan enkripsi data yang kuat untuk melindungi informasi.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("                <div class=\"card border-0 shadow h-100\">\r\n");
      out.write("                    <div class=\"card-body text-center p-4\">\r\n");
      out.write("                        <div class=\"feature-icon icon-performance text-white rounded-circle mb-4\">\r\n");
      out.write("                            <i class=\"bi bi-speedometer2\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h5 class=\"card-title fw-bold\">Performa Tinggi</h5>\r\n");
      out.write("                        <p class=\"card-text text-white\">Aplikasi dioptimalkan untuk memberikan pengalaman pengguna yang cepat dan responsif.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("                <div class=\"card border-0 shadow h-100\">\r\n");
      out.write("                    <div class=\"card-body text-center p-4\">\r\n");
      out.write("                        <div class=\"feature-icon icon-responsive text-white rounded-circle mb-4\">\r\n");
      out.write("                            <i class=\"bi bi-phone\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h5 class=\"card-title fw-bold\">Responsif</h5>\r\n");
      out.write("                        <p class=\"card-text text-white\">Tampilan yang adaptif pada berbagai perangkat dari desktop hingga mobile.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <!-- CTA Section -->\r\n");
      out.write("    <div class=\"py-5\">\r\n");
      out.write("        <div class=\"container py-4\">\r\n");
      out.write("            <div class=\"row align-items-center cta-container p-4\">\r\n");
      out.write("                <div class=\"col-lg-8\">\r\n");
      out.write("                    <h2 class=\"fw-bold neon-text\">Siap untuk memulai?</h2>\r\n");
      out.write("                    <p class=\"lead mb-0\">Daftar sekarang dan nikmati semua fitur yang tersedia.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 text-lg-end mt-3 mt-lg-0\">\r\n");
      out.write("                    <a href=\"register.jsp\" class=\"btn btn-primary btn-lg px-4 rounded-pill shadow\">\r\n");
      out.write("                        <i class=\"bi bi-person-plus me-2\"></i>Daftar\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Footer -->\r\n");
      out.write("    <footer class=\"py-4\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-6\">\r\n");
      out.write("                    <h5 class=\"mb-3 text-white\">Aplikasi JSP</h5>\r\n");
      out.write("                    <p class=\"text-muted\">Aplikasi web berbasis Java Server Pages dengan Bootstrap untuk tampilan yang menarik.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-3\">\r\n");
      out.write("                    <h5 class=\"mb-3 text-white\">Menu</h5>\r\n");
      out.write("                    <ul class=\"list-unstyled\">\r\n");
      out.write("                        <li><a href=\"#\" class=\"text-decoration-none link-light\">Beranda</a></li>\r\n");
      out.write("                        <li><a href=\"#\" class=\"text-decoration-none link-light\">Tentang</a></li>\r\n");
      out.write("                        <li><a href=\"#\" class=\"text-decoration-none link-light\">Kontak</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-3\">\r\n");
      out.write("                    <h5 class=\"mb-3 text-white\">Kontak</h5>\r\n");
      out.write("                    <ul class=\"list-unstyled\">\r\n");
      out.write("                        <li><i class=\"bi bi-envelope me-2\"></i>info@aplikasijsp.com</li>\r\n");
      out.write("                        <li><i class=\"bi bi-phone me-2\"></i>+62 123 4567 890</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <hr class=\"my-4\" style=\"border-color: rgba(255, 255, 255, 0.1);\">\r\n");
      out.write("            <div class=\"row align-items-center\">\r\n");
      out.write("                <div class=\"col-md-6 text-md-start\">\r\n");
      out.write("                    <p class=\"small mb-0 text-muted\">© 2025 Aplikasi JSP. Hak Cipta Dilindungi.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 text-md-end\">\r\n");
      out.write("                    <a href=\"#\" class=\"social-icon text-decoration-none link-light\"><i class=\"bi bi-facebook\"></i></a>\r\n");
      out.write("                    <a href=\"#\" class=\"social-icon text-decoration-none link-light\"><i class=\"bi bi-twitter\"></i></a>\r\n");
      out.write("                    <a href=\"#\" class=\"social-icon text-decoration-none link-light\"><i class=\"bi bi-instagram\"></i></a>\r\n");
      out.write("                    <a href=\"#\" class=\"social-icon text-decoration-none link-light\"><i class=\"bi bi-linkedin\"></i></a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Panggil Bootstrap JS lokal -->\r\n");
      out.write("    <script src=\"js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
